### PR TITLE
Add ext/random to manual.xml.in

### PR DESCRIPTION
**Pull request by TimWolla**
see php/doc-en#1916

### CODE REVIEW

**Comment by TimWolla** [comment]
Interesting, CI didn't fail, despite the entity not existing (yet, as expected):

https://github.com/php/doc-base/actions/runs/3324738526/jobs/5496677311#step:6:37

**Comment by cmb69** [comment]
> Interesting, CI didn't fail, despite the entity not existing (yet, as expected):

Yeah, that should be investigated closer.

**Comment by cmb69** [comment]
Anyway, we need to remove `&reference.csprng.book;` from this file.

**Comment by TimWolla** [comment]
> Anyway, we need to remove `&reference.csprng.book;` from this file.

Of course :facepalm: Thanks!

**Pull request merged**
