### PR TITLE
Update to PER CS coding style instead of PEAR

### PR DESCRIPTION
**Pull request by jimwins**
Doesn't seem to be any pushback on updating this, so let's do it

### CODE REVIEW

**Comment by jimwins** [comment]
Discussion here: https://news-web.php.net/php.doc/969388442

**Review by Crell — APPROVED** [review]

**Comment by Crell** [comment]
Not sure what the deal is with the failing builds, but the text looks good to me.

**Review by cmb69 — APPROVED** [review]
Thank you!

**Comment by cmb69** [comment]
@Crell, build failures are because some translations are not up to date (likely latest changes to MongoDB).

**Review by Girgias — APPROVED** [review]
Thank you for pushing this. :)

**Pull request merged**
