### PR TITLE
Remove url.crypt.blowfish entity

### PR DESCRIPTION
**Pull request by kamil-tekiela**
See https://github.com/php/doc-en/pull/1667 and https://github.com/php/web-php/pull/595

### CODE REVIEW

**Comment by cmb69** [comment]
As the CI failures show, several translations are not yet up to date for this. I suggest to wait some time before merging.

**Comment by cmb69** [comment]
Seems nothing has changed till now. Maybe provide PRs for the translations? Or just break these builds?

**Comment by kamil-tekiela** [comment]
> Or just break these builds?

I would be ok with that. As far as I know, it doesn't break the site, it just breaks new builds, correct?

**Review by cmb69 — APPROVED** [review]
> As far as I know, it doesn't break the site, it just breaks new builds, correct?

Right. And that should trigger a notification, so I think we should go ahead.

**Pull request merged**
