### PR TITLE
Simplify XInclude/XPointer error reporting.

### PR DESCRIPTION
**Pull request by alfsb**
This makes XInclude/XPointer error reporting less annoying, but doesn't omit them totally.

Impacts https://github.com/php/doc-base/pull/80 and https://github.com/php/doc-base/pull/85, end avoids the massive https://github.com/php/doc-en/pull/2015.

For https://github.com/php/doc-base/pull/85, I propose making the build fail only on `en/`, as making this a error on translations would kill (almost) them all.

### CODE REVIEW

**Review by Girgias — APPROVED** [review]
This looks sensible to me

**Comment by alfsb** [comment]
By coincidence, the manual is warning a XPointer failure on `en/`
```
XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.mongodb-bson-persistable')/db:refentry/db:refsect1[@role='description']/descendant::db:methodsynopsis[not(@role='procedural')])
```
I can merge a new commit, something like:
```php
if ( count( $errors ) && $ac['LANG'] == 'en' )
    errors_are_bad(1);
```
This will make the `en/` building to fail completely in case of failed XPointer evaluations, and will permit remove all xi:failbacks for the sake of translations, as we now have `--disable-xpointer-reporting`.

May I proceed directly, or open a specific issue about this?

**Comment by Girgias** [comment]
Probably open an issue first, so that this can be fixed and then make the build fail?

**Comment by Girgias** [comment]
Ah it already got fixed, so yes can be enabled now

**Pull request merged**
