### PR TITLE
Stop bugging Harald

### PR DESCRIPTION
**Pull request by cmb69**
See <https://github.com/php/doc-en/pull/3836>.

---

Likely fails for some translations. Let's see.

### CODE REVIEW

**Review by kamil-tekiela — APPROVED** [review]
Should we update all translations first?

**Comment by cmb69** [comment]
> Should we update all translations first?

I wouldn't know how to do that (except for German). Maybe we should just wait some days or weeks, and merge then.

**Comment by Girgias** [comment]
> > Should we update all translations first?
> 
> I wouldn't know how to do that (except for German). Maybe we should just wait some days or weeks, and merge then.

I thinking waiting for a couple of days and restarting the CI is a better idea. :)

**Comment by cmb69** [comment]
Just triggered CI again; most translations fail because of the MongoDB set to book conversion. I don't think adding this on top would be an issue.

**Pull request merged**
