### PR TITLE
Handle extensions state

### PR DESCRIPTION
**Pull request by jimwins**
Related to php/doc-en#3643.

### CODE REVIEW

**Comment by cmb69** [comment]
Great! Thank you @jimwins!

Note though that [checking out to `en` is customary](https://github.com/php/doc-base/blob/master/README.md#quick-reference), and looking for `doc-en` breaks the usual expectations.

I tried the script without the doc-en changes, and it works fine.

**Comment by cmb69** [comment]
@Girgias, since you've worked on that script, you may want to have a look.

**Comment by jimwins** [comment]
Okay, rebased without the `doc-en` change and fixed up my local setup.

**Review by Girgias — APPROVED** [review]
Did a quick review before I'm flying, but this looks sensible

**Comment by Girgias** [comment]
I'm confused why the CI is complaining about the extensions.xml file not being up to date

**Comment by cmb69** [comment]
I think the script would need to be run without the `--check` flag.

**Comment by jimwins** [comment]
Because now that the script handles State, doc-en *is* out of date. Thus php/doc-en#3645.

**Comment by cmb69** [comment]
And doc-en is green!

**Pull request merged**
